In [3]:
print("26-12-25\nFriday\nLong Term Internship") 

26-12-25
Friday
Long Term Internship


In [5]:
import numpy as np
arr1 = np.array([42])
print(arr1)

[42]


In [9]:
arr2 = np.array([1,2,3,4,5], ndmin=5)
print(arr2)
arr3 = np.array([[1,2,3],[4,5,6]])
print(arr3)
arr3.ndim

[[[[[1 2 3 4 5]]]]]
[[1 2 3]
 [4 5 6]]


2