In [1]:
print("11/12/2025")
print("Thursday")
print("Internship class")

11/12/2025
Thursday
Internship class


In [5]:
import numpy as np
print("Vectorization is used to remove the use of loops")
arr = np.array([1,2,3,4,5])
number = 10
result = arr + number
print(result)

Vectorization is used to remove the us of loops
[11 12 13 14 15]


In [9]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[0,1,2],[0,1,2]])
arr_sum = arr1+arr2
print(arr_sum)

[[1 3 5]
 [4 6 8]]


In [10]:
array = np.array([-1,0,1,2,3])
def find_Square(x):
    if x<0:
        return 0
    else :
        return x**2
vectorized_function = np.vectorize(find_Square)
result = vectorized_function(array)
print(result)

[0 0 1 4 9]


In [12]:
print("Broadcasting Arrays")
array1 = np.array([1,2,3])
array2 = np.array([[1],[2],[3]])
result = array2+array1
print(result)

Broadcasting Arrays
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [1]:
import pandas as pd

In [6]:
my_dataset = {'cars': ["BMW","VOLVO","FORD"],
                'PASSINGS' : [3,7,5]
}
print(my_dataset)

{'cars': ['BMW', 'VOLVO', 'FORD'], 'PASSINGS': [3, 7, 5]}


In [8]:
a=[1,2,3]
b=pd.Series(a)
print(b)

0    1
1    2
2    3
dtype: int64


In [10]:
print(b[0])

1


In [12]:
b=pd.Series(a,index=['x','y','z'])
print(b)

x    1
y    2
z    3
dtype: int64
